import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Header from "@/components/commons/header/header";
import Footer from "@/components/commons/footer/footer";
import {Toaster} from "sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className="flex flex-col min-h-screen">
        <Header/>
        <main className="flex-grow">{children}</main>
        <Footer/>
        <Toaster position="top-right"/>
        </body>
        </html>
    );
}
